environment = "staging"

[http]

[[http.server]]
listen = ["80"]
serverName = ["doudizhu-staging.sdkwork.com", "doudizhu-staging.birdcoder.com", "doudizhu-staging.dtupay.com", "doudizhu-staging.sdkwork.cn", "doudizhu-staging.birdcoder.cn", "doudizhu-staging.dtupay.cn", "doudizhu-staging.skubc.com", "doudizhu-staging.skubc.cn", "doudizhu-staging.zowalk.com", "doudizhu-staging.zowalk.cn", "doudizhu-staging.offer86.com", "doudizhu-staging.offer86.cn", "doudizhu-staging.86offer.com", "doudizhu-staging.86offer.cn"]
include = ["snippets/gateway-locations.nonproduction.conf"]

